name: update

on:
  schedule:
  - cron: "0 6 * * *"  # 3 AM Chile
  - cron: "0 10 * * *" # backup (7 AM Chile aprox)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python scripts/update_tasas.py

      - name: Verificar cambios
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain tasas.json)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit automático
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualizar tasas automático"
          file_pattern: tasas.json
